name = "application-dependencies-download"
main = "src/index.ts"
compatibility_date = "2022-06-12"

[[r2_buckets]]
binding = "dependencies_bucket"
bucket_name = "zlepper-video-application-dependencies"